AventusProtocolFoundation/avn-parachain

.github/workflows/ci.yml
.github/workflows/integration-test.yml
.gitignore
CODEOWNERS

- CI pipeline that runs on PR to main and on push to main with:
- cargo fmt check
- cargo test 
- cargo build
- Integration test that will be required to merge a PR but only runs with a manual trigger.
- Codeowners added 
**NOTES**
- The pipeline will only work after:
- doing a `cargo fmt` to the full repo
- updating [this file](https://github.com/Aventus-Network-Services/avn-node-parachain/blob/main/runtime/Cargo.toml) to include the staking pallet
- PR's from outside collaborators **must need** approval to run the CI - this is extremely important security wise. A read only secret to our `avn-node-parachain` can be **exploited/exposed** otherwise.
- github action used to install rust-toolchain has last commit from Nov 2020 - we should track this and potentially change to another action …

SYS-2752: GH actions for CI

---

.rustfmt.toml

Sets tab_spaces to 4 to match the original repo & team code style. https://github.com/rust-lang/rustfmt/blob/master/Configurations.md#tab_spaces

Adds tab_spaces to rustfmt.toml

---

pallets/parachain-staking/src/lib.rs
pallets/parachain-staking/src/mock.rs

This PR adds an extra requirement of registering session keys before becoming a collator.

SYS-2849 require session keys before joining as a collator

---

pallets/parachain-staking/src/benchmarks.rs
pallets/parachain-staking/src/lib.rs
pallets/parachain-staking/src/mock.rs
pallets/parachain-staking/src/nomination_requests.rs
pallets/parachain-staking/src/test_admin_settings.rs
pallets/parachain-staking/src/tests.rs
pallets/parachain-staking/src/types.rs

This PR renames:
-  `MinNominatorStake` -> `MinTotalNominatorStake` and 
- `MinNomination` -> `MinNominationPerCollator`
The first is the minimum total stake that must be maintained by a account to stay as a nominator. The second value is the minimum nomination they must maintain for each collator.

SYS-2851 update min nomination logic

---

pallets/parachain-staking/src/lib.rs
pallets/parachain-staking/src/migration.rs
pallets/parachain-staking/src/tests/bond_extra_tests.rs
pallets/parachain-staking/src/tests/nominate_tests.rs

This PR fixes a bug for nominate and bond_extra where rounding issues will attempt to nominate/bond more than what the user intended.
It also contains a small update to the default value of `min_user_stake` and fixes benchmark values.

SYS-2686 bug fix for rounding issues

---

pallets/parachain-staking/src/lib.rs

This PR fixes a bug where calling `signed_nominate` was exhausting the block weight.

SYS-3007 fix benchmark value on signed_nominate

---

pallets/avn-proxy/src/lib.rs
primitives/avn-common/src/lib.rs

This PR extends the signature verification logic in avn-proxy to handle wrapped payload generated by wallets such as polkadotJS.

SYS-3024 update signature verification to handle wrapped messages

---

pallets/avn-proxy/src/lib.rs
pallets/avn-proxy/src/tests/mock.rs
pallets/avn-proxy/src/tests/proxy_tests_no_fees.rs
pallets/avn-proxy/src/tests/proxy_tests_with_fees.rs
pallets/parachain-staking/src/tests/bond_extra_tests.rs
pallets/parachain-staking/src/tests/mock.rs
pallets/parachain-staking/src/tests/nominate_tests.rs
pallets/parachain-staking/src/tests/schedule_revoke_nomination_tests.rs
pallets/parachain-staking/src/tests/schedule_unbond_tests.rs

This PR reafactors avn-proxy pallet to be compatible with v0.9.28 or newer versions of substrate that make all extrinsics transactional.
Up to now, if an error occurred and the extrinsic got rejected, storage changes up to that point were persistent. Avn-proxy pallet was using this functionality to give the fees to the relayer account, when the inner call failed to complete.
In order to persist that behaviour, this PR makes changes on the interface and the behaviour of the system.
Proxied extrinsics that the inner call fails to execute for any reason will be accepted and an `InnerCallFailed` event will be emitted, with the original dispatch error. Fee charges will be persistent in storage.
If the proxied extrinsic fails validation, the behaviour remains the same as it was prior to this …

SYS-2850 Makes avn-proxy transactional compatible

---

pallets/token-manager/Cargo.toml

commit 6ea95c44fb7f631c9cfff8046239071fda6b9418 introduced default features flag, which breaks the pallets tests.
Projects cargo test was not affected. This PR rectifies this.

SYS-3123 Fixup token manager dependencies

---

pallets/avn/src/lib.rs
pallets/ethereum-transactions/src/ethereum_transaction.rs
pallets/ethereum-transactions/src/lib.rs
pallets/validators-manager/src/lib.rs
pallets/validators-manager/src/vote.rs

Reimplements the code that calculates the confirmations
Adds helper function that creates confirmations for calls that have their
arguments concatenated and hashed via keccak 256.
Uses the function above, to calculate confirmations for activate
collator, matching the expected values in avn-bridge.
Adds logs capturing the data generated and hashed.
Related JIRA items:
- SYS-3360
- SYS-3387

Aligns confirmation generation for adding collator

---

pallets/token-manager/src/lib.rs
pallets/token-manager/src/test_avt_tokens.rs

Fixes duplicate balance recording when performing AVT lifts and updates tests

SYS-3402 fix duplicate AVT balance recording

---

pallets/avn/src/lib.rs
pallets/validators-manager/src/lib.rs
pallets/validators-manager/src/mock.rs
pallets/validators-manager/src/tests_voting_deregistration.rs

This commit aligns the unit tests with the new implementation. It includes the following updates and fixes:
- Updates the mocks to use valid ECDSA signatures as confirmations.
- Modifies the test accounts to be derived from test private keys with a pattern of [1u8;32].
- Corrects internal logic in the tests that previously used the same AuthorityID for all validators.
- Removes tests that were specifically designed to test a mock implementation.
This PR rectifies any failing tests in #165

SYS-3333: Update and fix unit tests - Part 2

---

pallets/avn-transaction-payment/src/benchmarking.rs

This PR fixes a bug when running benchmark tests.

SYS-3347 fix benchmark tests

---

pallets/token-manager/src/lib.rs
pallets/token-manager/src/test_proxying_signed_transfer.rs

Removed duplicate transfer events by refactoring code in lib.rs. Updated tests to test for balances.Transfer instead of token-manager.TokenTransferred when testing AVT transfers.

SYS-3453: Removed duplicate transfer event and updated tests

---

pallets/validators-manager/src/lib.rs
pallets/validators-manager/src/tests/mock.rs
pallets/validators-manager/src/tests/tests.rs

This commit converts the ValidatorAccountIds storage item to a bounded Vector.
The vector is now limited to 256 elements. The necessary adjustments have been
made to the operations that interact with the storage, using the appropriate interfaces.
No storage migration is required for this conversion.
Tests have been updated accordingly to reflect the changes.

SYS-3338: Convert ValidatorAccountIds to Bounded Vector

---

pallets/token-manager/src/lib.rs
pallets/token-manager/src/test_avt_tokens.rs

Key Changes:
-TokenTransferred event call to only occur if the given token (token_id) is not avt 
-Updated settle_lower function parameters accordingly
-Updated tests accordingly
[SYS-3512](https://aventus-network-services.atlassian.net/browse/SYS-3512l)
[SYS-3512]: https://aventus-network-services.atlassian.net/browse/SYS-3512?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SYS-3512: move TokenTransferred event call and update tests

---

pallets/avn/src/lib.rs
pallets/avn/src/vote.rs
pallets/summary/Cargo.toml
pallets/summary/src/benchmarking.rs
pallets/summary/src/lib.rs
pallets/summary/src/tests/mock.rs
pallets/summary/src/tests/tests.rs
pallets/summary/src/vote.rs
pallets/validators-manager/src/benchmarking.rs
pallets/validators-manager/src/lib.rs
pallets/validators-manager/src/tests/mock.rs
pallets/validators-manager/src/vote.rs
primitives/avn-common/src/lib.rs

This commit converts the Voting mechanism in the summary and validators manager to use Bounded data structures. The changes include:
- Using BoundedVec for votes and confirmations
- Introducing WeakBoundedVec for the voting session ID (to be updated to BoundedVec in a separate change)
- Enabling storage information generation for the summary and validators manager pallets
- Adjusting function interfaces to handle potential failure when adding a vote
- Replacing Infallible paths with WeakBoundedVec as an interim solution
- Updating tests and benchmarks
- Resolving a dependency issue in benchmarks

SYS-3338: Convert Voting to Use Bounded Data Structures

---

Cargo.lock
pallets/avn/src/vote.rs
pallets/summary/Cargo.toml
pallets/summary/src/lib.rs
pallets/summary/src/tests/tests.rs
pallets/validators-manager/src/lib.rs
pallets/validators-manager/src/tests/tests.rs

Updates the Voting module to use `BoundedVec` instead of `WeakBoundedVec` for voting session IDs. The session IDs are now truncated using the `truncate` function to enforce the bounds of the data structure. It is important to ensure that the encoding of session IDs does not exceed the specified bounds.
To ensure this, tests have been added to verify that the constraints are properly enforced.

SYS-3338: Convert Voting Session ID to Use Bounded Data Structures

---

pallets/avn/src/vote.rs
pallets/nft-manager/src/batch_nft.rs
pallets/nft-manager/src/benchmarking.rs
pallets/nft-manager/src/lib.rs
pallets/nft-manager/src/nft_data.rs
pallets/nft-manager/src/tests/batch_nft_tests.rs
pallets/nft-manager/src/tests/cancel_single_nft_listing_tests.rs
pallets/nft-manager/src/tests/open_for_sale_tests.rs
pallets/nft-manager/src/tests/proxy_signed_cancel_list_fiat_nft_tests.rs
pallets/nft-manager/src/tests/proxy_signed_list_nft_open_for_sale_tests.rs
pallets/nft-manager/src/tests/proxy_signed_mint_single_nft_tests.rs
pallets/nft-manager/src/tests/proxy_signed_transfer_fiat_nft_tests.rs
pallets/nft-manager/src/tests/single_mint_nft_tests.rs
pallets/nft-manager/src/tests/transfer_to_tests.rs
pallets/summary/src/lib.rs
pallets/summary/src/tests/tests.rs
pallets/validators-manager/src/lib.rs
pallets/validators-manager/src/tests/tests.rs
primitives/avn-common/src/event_types.rs
primitives/avn-common/src/lib.rs

Updates the code, tests and Benchmarks to use a bound for external
references in storage.
Move constants into a separate module in avn-common crate.
Adds new tests to test the minting behaviour when the bound is not respected

SYS-3338 convert nft manager storage to bounded

---

pallets/avn-proxy/src/tests/mock.rs
pallets/nft-manager/src/batch_nft.rs
pallets/nft-manager/src/benchmarking.rs
pallets/nft-manager/src/lib.rs
pallets/nft-manager/src/nft_data.rs
pallets/nft-manager/src/tests/batch_nft_tests.rs
pallets/nft-manager/src/tests/cancel_single_nft_listing_tests.rs
pallets/nft-manager/src/tests/mock.rs
pallets/nft-manager/src/tests/open_for_sale_tests.rs
pallets/nft-manager/src/tests/proxy_signed_mint_single_nft_tests.rs
pallets/nft-manager/src/tests/transfer_to_tests.rs

Converts the code to use bounded data for Royalties and Batches. Updates tests, adds new ones that test the boundaries and updates benchmarks code.
Removes older migration code as all chains have been migrated and there is no value converting the old data struct.

SYS-3338 Converts Royalties and Batches size in bounded data

---

pallets/nft-manager/src/benchmarking.rs
pallets/nft-manager/src/lib.rs
pallets/nft-manager/src/tests/batch_nft_tests.rs
pallets/nft-manager/src/tests/proxy_signed_mint_single_nft_tests.rs

Convers UsedExternalReferences keys into WeakBoundedVector and adds migration that truncates and updates the keys where needed.
This is done as a stopgap solution, to transform any keys that exceed the bounds. Once all chains are successfully migrated, UsedExternalReferences will be reverted back to using Bounded Vectors
Review with conjunction to #194

SYS-3338 Adds migration for external reference

---

.github/workflows/cargo-test.yml

Rectifies some of the branch checks were missing the Rust installation step.

DEVOPS-365 Adds missing CI step

---

Cargo.lock
Cargo.toml
node/src/chain_spec/stable/mod.rs
pallets/avn-proxy/src/tests/mock.rs
pallets/avn/src/vote.rs
pallets/nft-manager/Cargo.toml
pallets/nft-manager/src/batch_nft.rs
pallets/nft-manager/src/benchmarking.rs
pallets/nft-manager/src/lib.rs
pallets/nft-manager/src/nft_data.rs
pallets/nft-manager/src/tests/batch_nft_tests.rs
pallets/nft-manager/src/tests/cancel_single_nft_listing_tests.rs
pallets/nft-manager/src/tests/mock.rs
pallets/nft-manager/src/tests/open_for_sale_tests.rs
pallets/nft-manager/src/tests/proxy_signed_cancel_list_fiat_nft_tests.rs
pallets/nft-manager/src/tests/proxy_signed_list_nft_open_for_sale_tests.rs
pallets/nft-manager/src/tests/proxy_signed_mint_single_nft_tests.rs
pallets/nft-manager/src/tests/proxy_signed_transfer_fiat_nft_tests.rs
pallets/nft-manager/src/tests/single_mint_nft_tests.rs
pallets/nft-manager/src/tests/transfer_to_tests.rs
pallets/parachain-staking/Cargo.toml
pallets/summary/src/lib.rs
pallets/summary/src/tests/tests.rs
pallets/validators-manager/src/lib.rs
pallets/validators-manager/src/tests/tests.rs
primitives/avn-common/Cargo.toml
primitives/avn-common/src/event_types.rs
primitives/avn-common/src/lib.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

Converts the nft manager storage items bounded.
This includes:
- batch size
- external references
- royalties
Added migration truncating and updating data that exceeded the boundaries
Updated tests and benchmarks
Updated log library std dependencies

SYS-3338 make nft manager storage items bounded

---

Cargo.lock
Cargo.toml
pallets/nft-manager/src/benchmarking.rs
pallets/nft-manager/src/lib.rs
pallets/nft-manager/src/tests/batch_nft_tests.rs
pallets/nft-manager/src/tests/proxy_signed_mint_single_nft_tests.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

Revert the stopgap solution for the migration and the migration code itself.
This should be included in a separate release from the original migration.
~Do not merge till #193 is merged and included in a release.~ - **Done**

SYS-3338 Finalises NFT manager data migration to bounded data structures

---

Cargo.lock
Cargo.toml
node/src/chain_spec/stable/mod.rs
pallets/avn-proxy/src/tests/mock.rs
pallets/avn/src/vote.rs
pallets/nft-manager/Cargo.toml
pallets/nft-manager/src/batch_nft.rs
pallets/nft-manager/src/benchmarking.rs
pallets/nft-manager/src/lib.rs
pallets/nft-manager/src/nft_data.rs
pallets/nft-manager/src/tests/batch_nft_tests.rs
pallets/nft-manager/src/tests/cancel_single_nft_listing_tests.rs
pallets/nft-manager/src/tests/mock.rs
pallets/nft-manager/src/tests/open_for_sale_tests.rs
pallets/nft-manager/src/tests/proxy_signed_cancel_list_fiat_nft_tests.rs
pallets/nft-manager/src/tests/proxy_signed_list_nft_open_for_sale_tests.rs
pallets/nft-manager/src/tests/proxy_signed_mint_single_nft_tests.rs
pallets/nft-manager/src/tests/proxy_signed_transfer_fiat_nft_tests.rs
pallets/nft-manager/src/tests/single_mint_nft_tests.rs
pallets/nft-manager/src/tests/transfer_to_tests.rs
pallets/parachain-staking/Cargo.toml
pallets/summary/src/lib.rs
pallets/summary/src/tests/tests.rs
pallets/validators-manager/src/lib.rs
pallets/validators-manager/src/tests/tests.rs
primitives/avn-common/Cargo.toml
primitives/avn-common/src/event_types.rs
primitives/avn-common/src/lib.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

Reintroduces 3c08ed8 commit but with the correct BatchNft bounds.
[Diff changes with 3.1.0 release](https://github.com/Aventus-Network-Services/avn-parachain/compare/v3.1.0...bb546d1d033c1a5a97f93209a19e8c90d6406a10)
Converts the nft manager storage items to bounded.
This includes:
- batch size
- external references
- royalties
Added migration truncating and updating data that exceeded the boundaries
Updated tests and benchmarks
Updated log library std dependencies

SYS-3338 make nft manager storage items bounded (2)

---

Cargo.lock
Cargo.toml
pallets/parachain-staking/src/benchmarks.rs
pallets/parachain-staking/src/lib.rs
pallets/parachain-staking/src/nomination_requests.rs
pallets/parachain-staking/src/set.rs
pallets/parachain-staking/src/tests/bond_extra_tests.rs
pallets/parachain-staking/src/tests/mock.rs
pallets/parachain-staking/src/tests/nominate_tests.rs
pallets/parachain-staking/src/tests/schedule_unbond_tests.rs
pallets/parachain-staking/src/tests/test_bounded_ordered_set.rs
pallets/parachain-staking/src/tests/test_growth.rs
pallets/parachain-staking/src/tests/tests.rs
pallets/parachain-staking/src/types.rs
pallets/token-manager/src/mock.rs
pallets/validators-manager/src/tests/mock.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

Reinstates commit 74ed078 and the work done on #198 
this PR introduces bounded data structures to parachain-staking
Related Jira items:
- SYS-3338

SYS-3555 convert parachain staking to bounded vec storage items (#198)

---

Cargo.lock
Cargo.toml
pallets/ethereum-transactions/src/benchmarking.rs
pallets/ethereum-transactions/src/ethereum_transaction.rs
pallets/ethereum-transactions/src/lib.rs
pallets/ethereum-transactions/src/mock.rs
pallets/ethereum-transactions/src/tests/tests.rs
pallets/summary/src/lib.rs
pallets/summary/src/tests/mock.rs
pallets/validators-manager/src/lib.rs
pallets/validators-manager/src/tests/mock.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

converted ethereum-transactions-pallet to use BoundedVec for the number of its validators

SYS-3556 Convert ethereum-transactions pallet to use BoundedVec

---

pallets/avn-finality-tracker/src/lib.rs
pallets/avn-offence-handler/src/lib.rs
pallets/avn/src/lib.rs
pallets/parachain-staking/src/lib.rs
pallets/token-manager/src/lib.rs

Removes the attribute `without_storage_info` from converted pallets.
This ensures that future development of the pallet will respect the bounded data structures prerequisite or throw an error during compilation

SYS-3338 Removes references of without_storage_info

---

Dockerfile.22_04
README.md

This commit introduces a Dockerfile tailored for building with Ubuntu 22.04, which is compatible with Debian 12 (bookworm) based OS due to its use of OpenSSL3. The Docker image generated includes the necessary dependencies.
Additionally, the README has been updated to provide clearer instructions on selecting the appropriate Dockerfile for different build scenarios.

Add Dockerfile for Ubuntu 22.04 (jammy) builds

---

pallets/avn/src/lib.rs
pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/util.rs
pallets/ethereum-transactions/src/lib.rs
pallets/parachain-staking/src/benchmarks.rs
pallets/parachain-staking/src/lib.rs
pallets/summary/src/benchmarking.rs
pallets/summary/src/lib.rs
pallets/validators-manager/src/benchmarking.rs
pallets/validators-manager/src/lib.rs
primitives/avn-common/src/lib.rs

OCW transaction processing logic was missing the condition to prevent sending whilst a tx still required confirmations. This is now added.
Additionally quorum getter has been refactored for clarity.

SYS-3630 Refactor quorum checking and fix eth-bridge OCW logic

---

pallets/avn/src/lib.rs
pallets/eth-bridge/src/call.rs
pallets/eth-bridge/src/eth.rs
pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/tests/mock.rs
pallets/eth-bridge/src/tx.rs
pallets/summary/src/lib.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

Various fixes to address issues arising during eth-bridge testing:
- Rename exit trait to align with entry trait
- Fix avn invoke method to handle leading slash on url and improve errors
- Fix view response processing for corroborate call
- Fix signing payload for extrinsics to use author's account id instead of entire author

SYS-3634 Fixes to: handler name, view response decoding, extrinsic payload signing, avn invoke method

---

pallets/eth-bridge/src/benchmarking.rs
pallets/eth-bridge/src/call.rs
pallets/eth-bridge/src/default_weights.rs
pallets/eth-bridge/src/eth.rs
pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/tests/mock.rs
pallets/eth-bridge/src/tests/tests.rs
pallets/eth-bridge/src/tx.rs

This PP changes the following (no functionality changes):
- updates `u32` -> `EthereumId`
- renames `ActiveTransaction` -> `ActiveRequest`
- renames `RequestData` -> `Request`
The rational behind the rename is to separate Transaction requests (sending a transaction to Ethereum) and lower proof requests (generating proofs for lower)

SYS-3773 Rename to allow support for non transaction requests - part 1

---

Cargo.lock
Cargo.toml
node/avn-service/src/lib.rs
pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/tests/tests.rs
pallets/eth-bridge/src/tx.rs
pallets/token-manager/src/lib.rs
pallets/token-manager/src/migration.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

This PR fixes a bug where ethereum events gets stuck processing invalid transaction hashes. It also adds a new event to signal retries and automatically sets expiry period during a forkless upgrade.

SYS-3773 Bug fix to handle bad transaction hashes and various improvements

---

Cargo.lock
Cargo.toml
pallets/parachain-staking/src/migration.rs
pallets/summary/Cargo.toml
pallets/summary/src/lib.rs
pallets/summary/src/migration.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

This PR adds a state migration to the summary pallet to avoid corrupting the roots data storage

SYS-3801 Adds state migration for summary pallet

---

pallets/ethereum-events/src/benchmarking.rs
pallets/summary/src/benchmarking.rs

This PR updates the benchmark for the Summary and Ethereum events pallet by taking into account MAX values of storage items.

SYS-3867 SYS-3865 Update benchmark for Summary and EthereumEvents

---

node/avn-service/src/ethereum_events_handler.rs
node/avn-service/src/lib.rs
pallets/eth-bridge/src/lib.rs
primitives/avn-common/src/event_discovery.rs
primitives/avn-common/src/lib.rs

Introduces the data structures and the voting mechanism for accepting events ranges from ethereum.
Ranges that are too big will be broken down into smaller partitions, voted upon individually, and accepted as one.
Follow up commit will do the validate unsigned and processing of the partitions.
Jira tickets:
- SYS-3635
- SYS-3930

SYS-3635: extends the voting mechanism

---

pallets/ethereum-events/src/lib.rs
pallets/ethereum-events/src/tests/tests.rs
pallets/token-manager/src/lib.rs
pallets/token-manager/src/mock.rs
pallets/token-manager/src/test_avt_tokens.rs
pallets/token-manager/src/test_common_cases.rs
pallets/token-manager/src/test_non_avt_tokens.rs
primitives/avn-common/src/event_types.rs
primitives/avn-common/src/tests/test_lower_claim.rs

Added LogLoweredClaimed event to primitives, add event handling and update token manager to consume the event.

SYS-3941 add log lowered claimed event

---

pallets/avn/src/lib.rs
pallets/eth-bridge/src/call.rs
pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/types.rs
primitives/avn-common/src/event_discovery.rs
primitives/avn-common/src/event_types.rs

This PR introduces support for processing votes upon achieving consensus. It extends extrinsics and data structures accordingly.
Once the final vote is cast, the voting round for the Ethereum range partition is finalized, and the partition is processed.
Additionally, this PR extends the subscription mechanism of the eth-bridge pallet. By default, pallets ignore processed events, requiring the implementation of a handler to process them.
Benchmarking for certain actions will be addressed in a separate PR.
Jira Tasks:
- SYS-3930
- SYS-3635

SYS-3930: Implement Vote Processing

---

node/avn-service/src/keystore_utils.rs
pallets/avn/src/lib.rs
pallets/ethereum-events/src/lib.rs
pallets/ethereum-events/src/tests/test_process_event.rs

From the auditors: 
```
The team identified that the application is using ".len()" and compares the return value with zero (0) to check if an array is empty. However, this is a more costly operation than using the faster ".is_empty()" function call.
```

SYS-3955 Improve length comparison

---

Cargo.lock
Cargo.toml
node/avn-lower-rpc/src/lib.rs
node/avn-service/src/lib.rs
pallets/avn-transaction-payment/src/tests/adjustment_fee_tests.rs
pallets/avn/src/lib.rs
pallets/eth-bridge/src/offence.rs
pallets/eth-bridge/src/tests/tests.rs
pallets/ethereum-events/src/event_parser.rs
pallets/ethereum-events/src/offence.rs
pallets/nft-manager/src/lib.rs
pallets/parachain-staking/src/tests/mock.rs
pallets/summary/src/offence.rs
pallets/validators-manager/src/lib.rs
pallets/validators-manager/src/proxy_tests/nominate_tests.rs
primitives/avn-common/src/event_types.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

This PR adds some minor improvements when doing checks to determine if a vector is empty or not. 

SYS-3955 Improve length comparison part 2

---

Cargo.lock
node/avn-service/src/ethereum_events_handler.rs
node/src/common.rs
node/src/service.rs
pallets/eth-bridge/src/lib.rs
primitives/avn-common/src/event_discovery.rs
primitives/avn-common/src/event_types.rs
runtime/avn/src/lib.rs

Adds a new endpoint that allows the chain to reach consenus over the initial ethereum range to be used.
This allows to simplify the voting logic for active ranges, eliminating the special case of the first range.

Introduces initial range consesnus mechanism

---

pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/tests/event_listener_tests.rs
pallets/eth-bridge/src/tests/mock.rs
pallets/eth-bridge/src/types.rs
pallets/summary/src/tests/mock.rs
primitives/avn-common/src/event_discovery.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

- General cleanup
- Rename of storage items
- Removal of mocks
- Wire up with runtime, implementing different events filters for each runtime.

SYS-3930 Cleanup and finalises interface with runtime

---

node/avn-service/src/ethereum_events_handler.rs
pallets/eth-bridge/runtime-api/src/lib.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

instead of `getting the author for current node`, as it requires `externalities`, we are exposing the `validators` storage item to iterate through to find the correct keystore public key

fix: refactored getting the authors to verify current node's author

---

node/avn-service/src/ethereum_events_handler.rs
pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/tests/incoming_events_tests.rs

This commit allows the avn-event-hanlder to handle more graceful error.
Also applies code formatting.

fix: Make avn-event-handler service more faullt tollerant

---

Dockerfile
Dockerfile.22_04

Fixes an issues with the container image generation, where the wrong path was used as the default execution path, leading to some errors when the node was trying to access the /data storage, resulting to this error:
`Os { code: 13, kind: PermissionDenied, message: \\"Permission denied\\"}`

fix: container image generation

---

pallets/eth-bridge/src/lib.rs

An event is marked as processed once the event processing logic is completed. The processing outcome of the pallet does not affect this.

fix: Issues with event processing

---

pallets/ethereum-events/src/lib.rs

Deprecates ethereum-events entry points that add manually events in the system.
Moving forward the responsibility will be shifted to eth-bridge event scanning mechanism on Ethereum.

SYS-3635 deprecate ethreum events entrypoints

---

node/avn-service/src/ethereum_events_handler.rs
pallets/eth-bridge/src/migration.rs
pallets/eth-bridge/src/tests/event_listener_tests.rs
pallets/eth-bridge/src/tests/incoming_events_tests.rs
primitives/avn-common/src/event_discovery.rs
runtime/avn/src/lib.rs

- Fixes an issue where the last block of a range was polled twice and included to the next range as well.
- Addresses feature PR feedback
- cleanup

SYS-3560 fix: ensures last block of a range is polled once

---

Cargo.lock
Cargo.toml
node/src/command.rs
pallets/eth-bridge/src/lib.rs
pallets/token-manager/src/migration.rs
runtime/test/src/lib.rs

This PR fixes the compilation error thrown when compiling the node with the `try-runtime` feature.

SYS-4125 Fix `try runtime` compilation error

---

pallets/ethereum-events/src/lib.rs
pallets/ethereum-events/src/mock.rs
pallets/ethereum-events/src/tests/test_ethereum_logs.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

Add filter to ethereum-events.

SYS-4144: Adding filter to ethereum-events

---

Cargo.lock
Cargo.toml
pallets/ethereum-events/src/mock.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

SYS-4116: Enable lift on eth-bridge

---

pallets/avn-proxy/src/tests/mock.rs
pallets/avn-proxy/src/tests/proxy_tests_with_fees.rs
pallets/token-manager/src/lib.rs

This PR fixes a bug where self pay proxy transactions were failing due to a bad proxy signature. New tests are also added to guard against this for the future.

SYS-4189 Fix nonce for self pay transactions

---

node/avn-service/src/ethereum_events_handler.rs
node/avn-service/src/keystore_utils.rs
node/avn-service/src/lib.rs
pallets/avn/src/lib.rs
primitives/avn-common/src/lib.rs

Improves avn-service checks to ensure signing operations are only performed when the node is correctly configured with a single Ethereum key in the keystore.
Additionally, enhances logging around signing operations for better visibility and eliminates multiple implementations of the ethereum hashing function.

feat: Enhance avn-service configuration and logging

---

pallets/avn/src/lib.rs
pallets/avn/src/mock.rs

Refactors mock of avn pallet:
- Introduces `TestDefaultConfig` for avn pallet to reduce mocks boilerplate code.
- uses `TestDefaultConfig` for avn pallet tests mocks for `frame_system` and `pallet_avn`

feat: Upgrade node to polkadot-sdk 1.6 - pallet avn mocks

---

pallets/avn/src/lib.rs
pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/tests/lower_proof_tests.rs
pallets/eth-bridge/src/tests/mock.rs
pallets/eth-bridge/src/tests/tests.rs
pallets/parachain-staking/src/lib.rs
pallets/summary/src/lib.rs
pallets/summary/src/tests/mock.rs
pallets/validators-manager/src/lib.rs
primitives/avn-common/src/lib.rs

Extract bridge contract names to Enum and fix Return type of `latest_finalised_ethereum_block`

Sys 4274/4275 extract smart contract names to an enum and fix return type of latest_finalised_ethereum_block

---

pallets/avn-offence-handler/src/lib.rs
pallets/avn-offence-handler/src/mock.rs

Additionally:
- Uses default test config for mocks
- Introduces and uses default test config for the pallet

fix: Tests setup for avn-offence handler

---

primitives/avn-common/src/lib.rs

To align with the account_id generation from ecdsa addresses in substrate

feat: Use blake 256 hash instead of keccak

---

Cargo.lock
Cargo.toml
pallets/avn/src/lib.rs
pallets/eth-bridge/src/benchmarking.rs
pallets/eth-bridge/src/default_weights.rs
pallets/eth-bridge/src/lib.rs
pallets/ethereum-events/src/lib.rs
primitives/avn-common/src/event_types.rs
primitives/avn-common/src/lib.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

This commit introduces the migration of processed events between the Ethereum Events and Eth-Bridge pallets.
Key details:
- The migration occurs during the `on_idle` callback.
- Failed migrations are restored to the original pallet for retry.
- In cases of multiple entries for the same key (transaction hash), the successfully processed entry takes precedence.
- Benchmarks for `on_idle` operations have been added, executed on a development machine.
- Benchmarks have been run locally on a Dev machine

feat: Add processed events migration

---

node/avn-service/src/ethereum_events_handler.rs
pallets/eth-bridge/runtime-api/src/lib.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

Extends the client to take into consideration the new api of additional events available from the runtime.
Upon receiving a list, the client will perform a search for that event and include it in the results if:
- the event is found
- its signature is part of the allowed ones
- the block number of the event is lower than the active range start limit
Jira ticket:
- SYS-4453

feat: extend the client to include additional events on discovery

---

node/avn-service/src/ethereum_events_handler.rs
pallets/eth-bridge/runtime-api/src/lib.rs
pallets/eth-bridge/src/benchmarking.rs
pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/migration.rs
pallets/eth-bridge/src/tests/event_listener_tests.rs
pallets/eth-bridge/src/tests/incoming_events_tests.rs
pallets/eth-bridge/src/types.rs
primitives/avn-common/src/event_discovery.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

- Transfer responsibility for checking if an additional event is within the range from `sudo` and client to the runtime.
- Simplify input by requiring only transaction IDs for the queues.
- Runtime dictates the dataset that node clients will attempt to discover.
- Ensure valid transactions are included in the range and trigger an event.
- Updates tests and benchmarks accordingly.
Jira ticket:
- SYS-4453

feat: Refactor additional transactions block constrains

---

Cargo.lock
Cargo.toml
node/avn-service/src/ethereum_events_handler.rs
pallets/eth-bridge/runtime-api/src/lib.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

Increase the runtime api and the way the client handles it. This enables the client binary to be forwards compatible with the introduction of the new API.
Jira ticket:
- SYS-4453

fix: Bumps the version of runtime api

---

pallets/authors-manager/src/mock.rs
pallets/avn-anchor/src/mock.rs
pallets/avn-proxy/src/tests/mock.rs
pallets/eth-bridge/src/benchmarking.rs
pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/tests/mock.rs
pallets/ethereum-events/src/lib.rs
pallets/ethereum-events/src/mock.rs
pallets/parachain-staking/src/tests/mock.rs
pallets/summary/src/tests/mock.rs
pallets/token-manager/src/mock.rs
pallets/validators-manager/src/tests/mock.rs
primitives/avn-common/src/event_discovery.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

- Refactors the trait name for filter handlers and simplifies filter creation.
- Adds sample filters used by runtimes.
- Updates EthereumEvents to consider event types specified in the filter rather than the remaining ones.
- Enables all core events on EthBridge.

chore: refactor and clean up Ethereum filters

---

pallets/authors-manager/src/mock.rs
pallets/avn-anchor/src/mock.rs
pallets/avn-offence-handler/src/mock.rs
pallets/avn-proxy/src/tests/mock.rs
pallets/avn/src/lib.rs
pallets/avn/src/mock.rs
pallets/eth-bridge/src/tests/mock.rs
pallets/ethereum-events/src/mock.rs
pallets/nft-manager/src/tests/mock.rs
pallets/summary/src/tests/mock.rs
pallets/token-manager/src/mock.rs
pallets/validators-manager/src/tests/mock.rs

The UintAuthorityId mock is not suitable as the default for the test implementation because it's not available in non-test configurations, which the default implementation relies on.
This commit sets the default AuthorityId to sr25519. Mocks explicitly restore UintAuthorityId where needed.

fix: update default AuthorityId in AVN pallet

---

pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/tests/incoming_events_tests.rs
pallets/eth-bridge/src/tests/tests.rs
pallets/eth-bridge/src/types.rs
primitives/avn-common/src/event_discovery.rs
primitives/avn-common/src/lib.rs
primitives/avn-common/src/tests/test_event_discovery.rs

Fixes an issue in the Ord implementation of DiscoveredEvent where event
ordering was based on the event signature instead of the transaction hash.
This caused inconsistent partitioning of the same dataset due to unstable
or incorrect ordering.
Ordering is now based on block number and transaction hash to guarantee
uniqueness and determinism.
Extends the set_admin_setting extrinsic to provide the option to reset
the vote data for ethereum events range.
Jira ticket:
- SYS-4548

fix: ensure stable ordering for Ethereum event partitions

---

.github/workflows/cargo-build.yml
.github/workflows/cargo-check.yml
.github/workflows/cargo-test.yml

Rust version should be mandated from rust-toolchain file for build operations.

fix: Remove manual rust installation step

---

.github/workflows/cargo-build.yml
.github/workflows/cargo-check.yml
.github/workflows/cargo-test.yml

To address building errors, rustup is not installed on the builders, leading to compilation errors.
Uses version 1.81.0 of rust onwards

Restores the rust installation step

---

pallets/avn-transaction-payment/src/lib.rs
pallets/avn-transaction-payment/src/tests/mock.rs
pallets/avn-transaction-payment/src/tests/set_known_sender_tests.rs
runtime/avn/src/lib.rs

This PR allows changing the origin for managing `known senders` in the runtime instead of hard coding it in the pallet.

Allow changing origin in runtime

---

Cargo.lock
Cargo.toml
pallets/authors-manager/src/benchmarking.rs
pallets/authors-manager/src/default_weights.rs
pallets/authors-manager/src/lib.rs
pallets/authors-manager/src/tests.rs
pallets/validators-manager/src/benchmarking.rs
pallets/validators-manager/src/default_weights.rs
pallets/validators-manager/src/lib.rs
pallets/validators-manager/src/tests/tests.rs
runtime/avn/src/lib.rs
runtime/test/src/lib.rs

Adds new sudo operation that allows to rotate the ethereum key of an existing author/validator.

feat: Enables rotation of Ethereum keys

---

pallets/eth-bridge/src/lib.rs
pallets/eth-bridge/src/offence.rs
pallets/eth-bridge/src/tests/mock.rs
pallets/eth-bridge/src/tx.rs
pallets/summary/src/tests/mock.rs

Address TODO and implement offences for invalid Ethereum ranges.
Revisits the slash_fraction implementation, mimicking the equivocation logic
and makes the offences generic for all cases.
References:
- M-05
- SYS-4662

feat: enable offences for invalid ethereum ranges votes

---

.github/workflows/cargo-build.yml
.github/workflows/cargo-check.yml
.github/workflows/cargo-test.yml
.github/workflows/ci-main.yml
.github/workflows/ci-pr.yml
rust-toolchain.toml

Upgrades rust to 1.85 to add support for 2024 edition which some of the newer crates depend on.
CI and toolchain files updated.
Removes fixed version of `cargo-edit` which was set due to lack of support to 2024 edition.

feat: upgrade to rust 1.85 stable

---

pallets/authors-manager/src/mock.rs
pallets/authors-manager/src/tests.rs
pallets/avn-offence-handler/src/mock.rs
pallets/avn-proxy/src/tests/mock.rs
pallets/ethereum-events/src/mock.rs
pallets/nft-manager/src/tests/mock.rs
pallets/parachain-staking/src/tests/mock.rs
pallets/summary/src/tests/mock.rs
pallets/summary/src/tests/tests.rs
pallets/summary/src/tests/tests_challenge.rs
pallets/summary/src/tests/tests_vote.rs
pallets/token-manager/src/mock.rs
pallets/validators-manager/src/tests/mock.rs

This removes related warnings and future proof the tests for future versions of Rust.

chore: Makes Avn pallet distinct from AVN type for mocks and tests

---

Cargo.lock
pallets/authors-manager/src/tests.rs
pallets/avn-proxy/Cargo.toml
pallets/avn-transaction-payment/Cargo.toml
pallets/avn/Cargo.toml
pallets/ethereum-events/Cargo.toml
pallets/nft-manager/Cargo.toml
pallets/summary/Cargo.toml
pallets/token-manager/Cargo.toml
pallets/validators-manager/Cargo.toml
pallets/validators-manager/src/tests/tests.rs
primitives/avn-common/src/tests/helpers.rs

This avoid compilation errors due to broken dependencies of bandersnatch_vrfs in older versions of polkadot-sdk.

fix: Tests dependencies to remove bandersnatch dependencies
