AventusProtocolFoundation/avn-parachain

pallets/parachain-staking/src/benchmarks.rs, pallets/parachain-staking/src/lib.rs, pallets/parachain-staking/src/mock.rs, pallets/parachain-staking/src/nomination_requests.rs, pallets/parachain-staking/src/set.rs, pallets/parachain-staking/src/test_staking_pot.rs, pallets/parachain-staking/src/tests.rs, pallets/parachain-staking/src/types.rs
=> SYS-2752 Rerunning formatting with the correct options

.github/workflows/integration-test.yml, CODEOWNERS
**WHAT**
- fix codeowners file
- fix CI
=> fix codeowners

.github/workflows/ci.yml
=> SYS-2752: CI fixed

.github/workflows/integration_test.yml
**WHAT**
- fix "sed" to work for forked repos
=> SYS-2752: fix forked integration test

.github/workflows/integration_test.yml
**WHAT**
- fix forked name repos
=> SYS-2572: fix repo name for forked PR's

.github/workflows/integration_test.yml
=> SYS-2752: typo

.github/workflows/integration_test.yml
=> SYS-2752: typo fixed

pallets/parachain-staking/src/types.rs
This PR removed deprecated types
=> SYS-2779 Remove deprecated types

.github/workflows/integration_test.yml
**WHAT**
- Integration test changed to fetch all pallets used on the public repo
**TESTS**
- tested locally but test on the CI needs to be done after merging
=> SYS-2758: integration test changed

.github/workflows/integration_test.yml
**WHAT**
- fix CI to make sure all cargo.toml are changed
=> SYS-2858: fix integration test bug

pallets/avn/src/lib.rs, pallets/parachain-staking/src/lib.rs, pallets/parachain-staking/src/tests/mock.rs, pallets/parachain-staking/src/tests/test_growth.rs
This PR handles any dust amount left after paying out collators.
=> SYS-2758 Handle dust amounts

pallets/parachain-staking/src/calls.rs, pallets/parachain-staking/src/lib.rs, pallets/parachain-staking/src/proxy_methods.rs
This PR adds logic for `signed_nominate`
=> SYS-2825 Flesh out `signed_nominate`

pallets/parachain-staking/src/lib.rs, pallets/parachain-staking/src/migration.rs, pallets/parachain-staking/src/tests/schedule_revoke_nomination_tests.rs, pallets/parachain-staking/src/tests/schedule_unbond_tests.rs
Adds current version to the pallet and updates the pallet code to handle the different upgrade paths
Removes dead code and warnings from tests.
Jira items:
- SYS-3111
=> Fixes upgrade path for staking pallet

.github/workflows/ci.yml, .github/workflows/integration_test.yml
**WHAT**
- add avn-runner to run on CI jobs
- add concurrency limit per branch
=> NO_JIRA: add avn-runner to repo

.github/workflows/ci.yml, .github/workflows/integration_test.yml
**WHAT**
- fix concurrency issue
=> concurrency fix

Cargo.lock, pallets/token-manager/Cargo.toml
Fixes references to other pallets for token manager, as two different version were used.
=> SYS-3123 Fixes references to token-manager toml

pallets/summary/Cargo.toml
This is to resolve the summary pallet problem when compiling on the main runtime. This fixes the problem caused in ticket SYS-3135
Before you submit a PR, please check that:
✄ -----------------------------------------------------------------------------
=> Sys 3135 summary pallet compilation problem

Cargo.lock, pallets/token-manager/Cargo.toml
Added a dependency to token-manager pallet
=> NO_JIRA - added a dependency to token-manager pallet

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/general-question-.md
Create templates to help organise issues and for automatic assignments.
=> Update issue templates

.github/workflows/ci.yml
AFTER YOU'VE READ THIS NOTICE, FEEL FREE TO REMOVE IT.
Thank you!
Before you submit a PR, please check that:
✄ -----------------------------------------------------------------------------
=> Devops-14 Change ci of avn-parachain

Cargo.lock, pallets/ethereum-transactions/src/ethereum_transaction.rs, pallets/validators-manager/Cargo.toml, pallets/validators-manager/src/lib.rs, pallets/validators-manager/src/mock.rs, pallets/validators-manager/src/tests.rs
This pr adjusts the interface of the registerValidator function that interfaces with the smart contract. Additionally tests are refactored to run properly and additional util function to decompress eth_public_key
Before you submit a PR, please check that:
✄ -----------------------------------------------------------------------------
=> SYS-3360 - adjusted registerValidator interface and tests

Cargo.lock, pallets/avn-transaction-payment/Cargo.toml, pallets/avn-transaction-payment/src/lib.rs
This PR creates a new pallet called `avn-transaction-payment` which is a wrapper for transaction-payment that will have some extra business logic.
=> SYS-3373 Setup new pallet

Cargo.lock, pallets/ethereum-transactions/src/ethereum_transaction.rs, pallets/ethereum-transactions/src/lib.rs, pallets/validators-manager/src/lib.rs, pallets/validators-manager/src/mock.rs, pallets/validators-manager/src/tests.rs, pallets/validators-manager/src/vote.rs, primitives/avn-common/Cargo.toml, primitives/avn-common/src/eth_key_actions.rs, primitives/avn-common/src/lib.rs, primitives/avn-common/src/tests/test_eth_key_actions.rs
This is redo of a previous PR, this time appending a new struct instead of modifying the already present struct
=> SYS-3360 - registerCollator

pallets/avn-transaction-payment/src/lib.rs, pallets/avn-transaction-payment/src/tests/mock.rs
What: Mock file changes for Discount tests and lib.rs minor change.
=> SYS-3357 Mock file changes

pallets/avn-transaction-payment/src/fee_adjustment_config.rs
What: Quick fix for Adjustment type is_active method.
=> SYS-3357 Adjustment type fix

pallets/avn-transaction-payment/src/fee_adjustment_config.rs, pallets/avn-transaction-payment/src/lib.rs
This PR updates the refund calculation logic
=> SYS-3357 update refund logic

pallets/avn-transaction-payment/src/lib.rs, pallets/avn-transaction-payment/src/tests/adjustment_fee_tests.rs, pallets/avn-transaction-payment/src/tests/discount_fee_tests.rs
What: Tests that check the fees after different discounts are applied.
=> SYS-3357 Discount tests suite

pallets/avn-transaction-payment/src/fee_adjustment_config.rs, pallets/avn-transaction-payment/src/lib.rs, pallets/avn-transaction-payment/src/tests/adjustment_fee_tests.rs, pallets/avn-transaction-payment/src/tests/mock.rs, pallets/avn-transaction-payment/src/tests/set_known_sender_tests.rs
This PR adds event checks for unit tests and a small test logic fix
=> SYS-3357 add event checks for tests

pallets/avn-transaction-payment/src/fee_adjustment_config.rs, pallets/avn-transaction-payment/src/tests/adjustment_fee_tests.rs
What: Flexi fee transaction based fix.
=> Flexi fee transaction based fix

pallets/avn-transaction-payment/src/lib.rs, pallets/avn-transaction-payment/src/tests/adjustment_fee_tests.rs
This PR fixes 2 bugs:
- Tips are not affected by adjustments anymore
- Default refund logic is re-instated
=> SYS-3483, SYS-3484 - Fix default refund and tip logic

pallets/token-manager/src/lib.rs
fixed the bounded length of the TokenId and TokenBalance
=> sys-3338 - convert token manager bounded

Cargo.lock, pallets/nft-manager/Cargo.toml, pallets/nft-manager/src/batch_nft.rs, pallets/nft-manager/src/lib.rs, pallets/nft-manager/src/tests/batch_nft_tests.rs, pallets/nft-manager/src/tests/mock.rs, pallets/nft-manager/src/tests/proxy_signed_mint_single_nft_tests.rs, pallets/nft-manager/src/tests/proxy_signed_transfer_fiat_nft_tests.rs, pallets/nft-manager/src/tests/single_mint_nft_tests.rs, pallets/nft-manager/src/tests/transfer_to_tests.rs
Adds a migration that drops OwnedNfts
Updates pallet version to use the new pallet versioning schema
=> SYS-3338 Drops OwnedNfts storage item

pallets/token-manager/src/benchmarking.rs
fixed token-manager benchmarks
=> removed check for avt_lowered event

.github/workflows/ci.yml
AFTER YOU'VE READ THIS NOTICE, FEEL FREE TO REMOVE IT.
Thank you!
Before you submit a PR, please check that:
✄ -----------------------------------------------------------------------------
=> DEVOPS-346 Enhance avn-parachain CI to test Benchmarks code

pallets/parachain-staking/Cargo.toml, primitives/avn-common/Cargo.toml
Updates the log crate features and dependencies to fixup runtime build issues.
=> SYS-3338 log dependencies fixup

README.md
Updates the project README with relevant information for the project now that it includes the client and runtime crates.
=> SYS-3521 Update project README

Cargo.lock, Cargo.toml, node/Cargo.toml, node/avn-service/Cargo.toml
To inherit version from the project minimising the diff when updating the version
Ports changes that occurred after migrating the codebase
=> SYS-3521 Update project module cargo configuration

.github/workflows/cargo-test.yml
=> DEVOPS-365 fixed CI issues

node/src/chain_spec/stable/mod.rs, pallets/nft-manager/src/lib.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
Adds runtime interface changes.
Updates the genesis state of the pallet to store the current version of the database version upon genesis.
=> SYS-3338 Finalise feature branch

pallets/parachain-staking/src/benchmarks.rs, pallets/parachain-staking/src/lib.rs, pallets/parachain-staking/src/nomination_requests.rs, pallets/parachain-staking/src/set.rs, pallets/parachain-staking/src/tests/bond_extra_tests.rs, pallets/parachain-staking/src/tests/mock.rs, pallets/parachain-staking/src/tests/nominate_tests.rs, pallets/parachain-staking/src/tests/schedule_unbond_tests.rs, pallets/parachain-staking/src/tests/test_bounded_ordered_set.rs, pallets/parachain-staking/src/tests/test_growth.rs, pallets/parachain-staking/src/tests/tests.rs, pallets/parachain-staking/src/types.rs, pallets/token-manager/src/mock.rs, pallets/validators-manager/src/tests/mock.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
Converted `pallet-parachain-staking` to use BoundedVec and implement MaxEncodedLen
=> Sys 3338 convert parachain staking to bounded vec storage items

pallets/nft-manager/src/lib.rs, pallets/nft-manager/src/tests/sanitise_external_ref_tests.rs, pallets/nft-manager/src/tests/sanitise_nft_data_tests.rs
Ensures that nfts external references is within the expected bounds.
=> SYS-3338 Adds sudo extrinsic that sanistises the external reference

README.md
This PR updates the readme
There are no code changes here.
=> SYS-3646 Update readme

Cargo.lock, Cargo.toml, pallets/avn/src/lib.rs, pallets/ethereum-events/src/mock.rs, primitives/avn-common/src/event_types.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
converted avn-pallet to use BoundedVec for the number of its validators
=> converted avn-pallet to use boundedvec

.github/workflows/cargo-test.yml
fixed Runtime Benchmarks on PR workflow 
=> DEVOPS-457 fix PR workflows on anv-parachain repo

pallets/parachain-staking/src/lib.rs, pallets/parachain-staking/src/nomination_requests.rs, pallets/parachain-staking/src/set.rs, pallets/parachain-staking/src/tests/mock.rs, pallets/parachain-staking/src/tests/test_bounded_ordered_set.rs, pallets/parachain-staking/src/tests/tests.rs, pallets/parachain-staking/src/types.rs, pallets/validators-manager/src/lib.rs
This commit improves the previous work by consuming and handling errors when they occur.
On the back of that, some validators manager tests started to fail as the interaction with staking pallet can fail due to reaching the candidates bound. This has been addressed with an early check so the errors are consistent with the validators manager pallet.
Finally some unused interfaces and tests have been removed.
=> SYS-3555 Improves error handling

pallets/ethereum-events/src/tests/test_parse_event.rs, pallets/token-manager/src/mock.rs, primitives/avn-common/src/event_types.rs, primitives/avn-common/src/tests/test_event_types.rs
Updated LiftedData parameters and LogLifted event signature removing tier 1 address.
=> SYS-3640 update LogLifted event signature

Cargo.lock, Cargo.toml, pallets/ethereum-events/src/tests/test_parse_event.rs, pallets/token-manager/src/mock.rs, primitives/avn-common/src/event_types.rs, primitives/avn-common/src/tests/test_event_types.rs
Reverts Aventus-Network-Services/avn-parachain#243
=> Revert "SYS-3640 update LogLifted event signature"

pallets/ethereum-events/src/tests/test_parse_event.rs, pallets/token-manager/src/mock.rs, primitives/avn-common/src/event_types.rs, primitives/avn-common/src/tests/test_event_types.rs
Updated LiftedData parameters and LogLifted event signature removing tier 1 address.
=> Sys 3640 log lifted event signature

Cargo.lock, Cargo.toml, pallets/avn-finality-tracker/src/mock.rs, pallets/avn-offence-handler/src/mock.rs, pallets/avn-proxy/src/tests/mock.rs, pallets/avn/src/lib.rs, pallets/avn/src/mock.rs, pallets/avn/src/tests/test_set_bridge_contract.rs, pallets/ethereum-events/src/lib.rs, pallets/ethereum-events/src/mock.rs, pallets/ethereum-transactions/src/lib.rs, pallets/ethereum-transactions/src/mock.rs, pallets/nft-manager/src/tests/mock.rs, pallets/parachain-staking/src/tests/mock.rs, pallets/summary/src/tests/mock.rs, pallets/token-manager/src/mock.rs, pallets/validators-manager/src/tests/mock.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
This PR adds a new event when the avn bridge contract address changes.
=> SYS-3369 Add event when updating avn bridge contract

Cargo.lock, Cargo.toml, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
=> SYS-3665 create new release with runtime increase

pallets/avn-finality-tracker/src/lib.rs, pallets/avn/src/lib.rs, pallets/ethereum-transactions/src/lib.rs, pallets/ethereum-transactions/src/tests/tests.rs, pallets/parachain-staking/src/benchmarks.rs, pallets/parachain-staking/src/lib.rs, pallets/summary/src/benchmarking.rs, pallets/summary/src/lib.rs, pallets/summary/src/tests/mock.rs, pallets/summary/src/tests/tests_challenge.rs, pallets/summary/src/tests/tests_slot_logic.rs, pallets/summary/src/tests/tests_vote.rs, pallets/validators-manager/src/benchmarking.rs, pallets/validators-manager/src/lib.rs, primitives/avn-common/src/lib.rs
Re-adding the previously reviewed quorum work on this fresh feature branch
=> SYS-3630 Update quorum calculation

runtime/avn/src/governance/mod.rs, runtime/test/src/governance/mod.rs
Added an entity to collect slashed deposits, so that we don't lose avt on every killed referendum.
=> add slashing entity

pallets/avn/src/lib.rs, pallets/eth-bridge/src/lib.rs, pallets/summary/src/lib.rs, runtime/avn/src/lib.rs
=> SYS-3560 State migration to seed transactionId

pallets/eth-bridge/src/eth.rs
This should fix the corroborate call. 
Outputs are removed as these aren't required for constructing the calldata, which is all the ethabi Function object is actually being used for.
=> SYS-3634 Fix corroborate check

pallets/eth-bridge/src/benchmarking.rs
Fix benchmark tests for eth bridge pallet
=> SYS-3634 Fix benchmark tests

Cargo.lock, pallets/eth-bridge/Cargo.toml, pallets/eth-bridge/src/eth.rs, pallets/eth-bridge/src/lib.rs, pallets/eth-bridge/src/offence.rs, pallets/eth-bridge/src/tests/mock.rs, pallets/eth-bridge/src/tx.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
Adding offences to eth-bridge, tests will be added in a follow-up pr
=> Sys 3732 wireup offence pallet

node/src/chain_spec/stable/local.rs
This PR increases the number of collators to 4 for a local chain
=> SYS-3741 Increase the number of collators to 4 for a local chain

Cargo.lock, pallets/validators-manager/Cargo.toml, pallets/validators-manager/src/lib.rs, pallets/validators-manager/src/migration.rs, runtime/avn/src/lib.rs
created a migration to remove storage items that were cleaned up in code
=> added migration to drop storage items

pallets/summary/src/tests/mock.rs, pallets/summary/src/tests/test_ocw_locks.rs, pallets/summary/src/tests/tests.rs
=> SYS-3632 Fix summary tests

node/src/chain_spec/stable/mod.rs, node/src/chain_spec/test/mod.rs, pallets/token-manager/Cargo.toml, pallets/token-manager/src/lib.rs, pallets/token-manager/src/migration.rs, pallets/token-manager/src/mock.rs
This PR implements a configurable schedule period (in block number) where a lower transaction waits before being executed
=> SYS-3722 Lower schedule period

Cargo.lock, pallets/token-manager/src/lib.rs, pallets/token-manager/src/migration.rs
This PR integrates TokenManager with EthBridge
=> SYS-3719 Integrates TokenManager with EthBridge

Cargo.lock, pallets/token-manager/Cargo.toml, pallets/token-manager/src/lib.rs, pallets/token-manager/src/mock.rs, pallets/token-manager/src/test_avt_tokens.rs, pallets/token-manager/src/test_common_cases.rs, pallets/token-manager/src/test_non_avt_tokens.rs, pallets/token-manager/src/test_proxying_signed_lower.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
This PR fixes the existing lower tests
=> SYS-3751 fix existing lower tests

Cargo.lock, Cargo.toml, node/src/chain_spec/stable/local.rs, node/src/chain_spec/stable/staging.rs, node/src/chain_spec/test/local.rs, node/src/chain_spec/test/staging.rs
This PR updates the AVT and AVN contracts in the chainspec. 
=> SYS-3818 Update AVT and AVN contracts in the chainspec

.github/workflows/cargo-build.yml, .github/workflows/cargo-check.yml, .github/workflows/cargo-test.yml
Updated github actions in preparation for the upgrade to polkadot-v1.0.0
=> SYS-3828: updated github actions

Cargo.lock, Cargo.toml, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
Rectifies missing runtime version bump from 5.2.1 release.
=> Increases the runtime version

pallets/eth-bridge/src/lib.rs
Updates the validate unsigned function to support
submit_discovered_events extrinsic.
Jira tickets:
- SYS-3635
- SYS-3930
=> SYS-3930: Extends validate unsigned for new extrinsic

Cargo.lock, Cargo.toml, pallets/avn/src/lib.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
=> Small change just to create a new release

pallets/eth-bridge/src/benchmarking.rs
=> SYS-3961 Include max confirmation in benchmarks - Improvement

pallets/eth-bridge/src/benchmarking.rs, pallets/eth-bridge/src/lib.rs, runtime/avn/src/lib.rs
=> Sys 3957 fmt

Cargo.lock, node/avn-service/src/ethereum_events_handler.rs, node/src/chain_spec/test/mod.rs, pallets/eth-bridge/runtime-api/src/lib.rs, pallets/eth-bridge/src/call.rs, pallets/eth-bridge/src/lib.rs, pallets/eth-bridge/src/tests/event_listener_tests.rs, primitives/avn-common/src/event_discovery.rs, runtime/avn/src/lib.rs, runtime/test/Cargo.toml, runtime/test/src/lib.rs
This commit includes the integration of the initial range voting functionality with the client.
It ports changes to integrate the runtime API for testing runtime behavior.
Additionally, it refactors the runtime API to improve proof creation by relocating helper
functions to primitive crates.
Fixes genesis config for test runtime.
Jira tasks:
- SYS-3930
- SYS-3635
=> Integrate initial range voting with client and refactor runtime API

node/avn-service/src/ethereum_events_handler.rs, pallets/avn/src/lib.rs, pallets/eth-bridge/runtime-api/src/lib.rs, pallets/eth-bridge/src/lib.rs, primitives/avn-common/src/event_discovery.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
This commit addresses issues with extrinsic submission in the runtime:
- Registers the extension to the instance submitting the extrinsic.
- Updates signature validation.
- Simplifies interface and error handling via the runtime API, following the report_equivocation style.
=> fix: client extrinsics operation

pallets/nft-manager/Cargo.toml, pallets/nft-manager/src/lib.rs, pallets/token-manager/src/lib.rs, runtime/avn/src/lib.rs, runtime/test/Cargo.toml, runtime/test/src/lib.rs
Adds handlers in Token manager and wire up for Runtime to process the first type of events from eth-bridge.
Jira ticket:
- SYS-4072
=> SYS-4072 fix handling of eth-bridge processed events

pallets/eth-bridge/src/benchmarking.rs, pallets/eth-bridge/src/lib.rs, pallets/eth-bridge/src/migration.rs, pallets/eth-bridge/src/tests/event_listener_tests.rs, primitives/avn-common/src/event_discovery.rs
Use checked fucntions to do the mod calculations.
Updates tests, benchmarks and resto of the code accordingly
Restores batch value to tested.
=> fix: Runtime panic and upgrade migration issues

node/avn-service/src/ethereum_events_handler.rs
Adds AvtLowerClaimedData in the types the client scans. Fixes the way the data field is constructed ensuring the data field is explicitly set as None when no data is present, to align with the runtime implementation.
=> fix: event parsing and adds test case

node/src/service.rs
This PR adds a fix to AvN service to store the port number in the OCW's database.
=> SYS-4078 Port avn service port fix

Cargo.lock, pallets/avn-anchor/Cargo.toml, pallets/avn-anchor/src/benchmarking.rs, pallets/avn-anchor/src/lib.rs, pallets/avn-anchor/src/mock.rs, pallets/avn-anchor/src/tests.rs, runtime/avn/Cargo.toml, runtime/avn/src/lib.rs
Initial implementation of `register_chain_handler` and `update_chain_handler`
=> Sys 4191 register chain handler

pallets/summary/src/lib.rs, pallets/summary/src/tests/anchor_tests.rs, pallets/summary/src/tests/mock.rs, pallets/summary/src/tests/tests.rs, pallets/summary/src/tests/tests_challenge.rs, pallets/summary/src/tests/tests_vote.rs
=> SYS-4250 New test for anchor summary

Cargo.lock, Cargo.toml, node/src/chain_spec/stable/mod.rs, node/src/chain_spec/test/mod.rs, pallets/summary/src/benchmarking.rs, pallets/summary/src/challenge.rs, pallets/summary/src/lib.rs, pallets/summary/src/offence.rs, pallets/summary/src/tests/anchor_tests.rs, pallets/summary/src/tests/mock.rs, pallets/summary/src/tests/test_ocw_locks.rs, pallets/summary/src/tests/tests.rs, pallets/summary/src/tests/tests_challenge.rs, pallets/summary/src/tests/tests_slot_logic.rs, pallets/summary/src/tests/tests_validate_unsigned.rs, pallets/summary/src/tests/tests_vote.rs, pallets/summary/src/vote.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
This PR contains all the summary pallet changes (2 separate PRs)
=> SYS-4254 Summary pallet change feature merge

Cargo.lock, node/Cargo.toml, node/avn-lower-rpc/Cargo.toml, node/avn-service/Cargo.toml, pallets/avn-anchor/Cargo.toml, pallets/avn-offence-handler/Cargo.toml, pallets/avn-proxy/Cargo.toml, pallets/avn-transaction-payment/Cargo.toml, pallets/avn/Cargo.toml, pallets/eth-bridge/Cargo.toml, pallets/eth-bridge/runtime-api/Cargo.toml, pallets/eth-bridge/runtime-api/src/lib.rs, pallets/ethereum-events/Cargo.toml, pallets/ethereum-events/src/lib.rs, pallets/nft-manager/Cargo.toml, pallets/parachain-staking/Cargo.toml, pallets/summary/Cargo.toml, pallets/token-manager/Cargo.toml, pallets/validators-manager/Cargo.toml, primitives/avn-common/Cargo.toml, runtime/avn/Cargo.toml, runtime/common/Cargo.toml, runtime/test/Cargo.toml, rust-toolchain.toml
Upgrade the project references to use version 1.6 of the polkadot-sdk.
=> feat: upgrade references to polkadot 1.6

Cargo.lock, node/Cargo.toml, node/avn-lower-rpc/Cargo.toml, node/avn-service/Cargo.toml, pallets/avn-anchor/Cargo.toml, pallets/avn-offence-handler/Cargo.toml, pallets/avn-proxy/Cargo.toml, pallets/avn-transaction-payment/Cargo.toml, pallets/avn/Cargo.toml, pallets/eth-bridge/Cargo.toml, pallets/eth-bridge/runtime-api/Cargo.toml, pallets/eth-bridge/runtime-api/src/lib.rs, pallets/ethereum-events/Cargo.toml, pallets/ethereum-events/src/lib.rs, pallets/nft-manager/Cargo.toml, pallets/parachain-staking/Cargo.toml, pallets/summary/Cargo.toml, pallets/token-manager/Cargo.toml, pallets/token-manager/src/lib.rs, pallets/validators-manager/Cargo.toml, primitives/avn-common/Cargo.toml, runtime/avn/Cargo.toml, runtime/common/Cargo.toml, runtime/test/Cargo.toml, rust-toolchain.toml
This commit changes the way token manager interacts with the preimage pallet, via the scheduler pallet, since the deposit mechanism has been altered.
=> feat: upgrade to polkadot-sdk 1.6 - token manager

node/src/rpc.rs
The endpoint was previously deprecated and will no longer be maintained.
=> feat!: Remove deprecated lower_data RPC endpoint

runtime/avn/Cargo.toml, runtime/test/Cargo.toml
Some of the changes were not included on #452
=> fix: Updates Cargo toml for runtime

pallets/ethereum-events/src/benchmarking.rs, pallets/ethereum-events/src/lib.rs, pallets/ethereum-events/src/mock.rs
Additionally:
- Uses default test config for mocks
- Introduces and uses default test config for the pallet
=> fix: Tests setup for avn-events pallet

Cargo.lock, Cargo.toml, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
Increased spec version to facilitate clean follow up upgrade 
=> fix: increase spec version in preparation of anchoring fees release

pallets/avn-proxy/src/tests/mock.rs, pallets/avn-proxy/src/tests/proxy_tests_no_fees.rs, pallets/eth-bridge/src/eth.rs, primitives/avn-common/src/lib.rs
This PR updates the hashing algorith to match external ethereum wallets.
=> update ethereum hasher

pallets/eth-bridge/src/tests/mock.rs, pallets/ethereum-events/src/mock.rs, pallets/summary/src/tests/mock.rs, pallets/summary/src/tests/tests.rs, pallets/summary/src/tests/tests_challenge.rs, pallets/summary/src/tests/tests_vote.rs
Updates the pallets, mocks and benchmarks to be compatible with the polkadot-sdk 1.6
=> Upgrade summary and eth-bridge to sdk 1.6

Cargo.lock, Cargo.toml, rust-toolchain.toml
Updates the release-1.1 branch to use the latest version to bypass some build errors due to a missing crate.
Updates toolchain to 1.81.0
=> feat: Update polkadot release branch to latest

Cargo.lock, Cargo.toml, node/avn-service/src/ethereum_events_handler.rs
- Extends client and runtime to support discovery of direct ERC-20 transfers to the bridge contract.
- Identifies primary and secondary events, ensuring only transfers not associated with a primary event are processed.
- Event filtering is a responsibility of the collators, which submit validated data to the chain.
- Adds configurable vault account to hold the directly lifted tokens
Related Jira ticket:
- SYS-4349
=> feat: Introduces automatic lifts of ERC-20 token transfers to bridge contract

Cargo.lock, Cargo.toml, pallets/avn-proxy/Cargo.toml, pallets/avn-proxy/src/tests/mock.rs, pallets/avn-proxy/src/tests/proxy_tests_no_fees.rs, primitives/avn-common/src/lib.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
=> SYS-4356 Update key derivation and fix ecdsa test signing

pallets/eth-bridge/runtime-api/src/lib.rs, pallets/eth-bridge/src/lib.rs, pallets/eth-bridge/src/migration.rs, pallets/eth-bridge/src/types.rs, primitives/avn-common/src/event_discovery.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
- Extend data structures to enable additional events on selected ranges.
- Implement storage for queuing additional ethereum events.
- Update active range to contain designated additional events.
- Develop database migration for existing storage items.
- Assigns queued additional events to the next range upon activation.
- Enhance runtime API interface and runtime implementation to provide the additional event data.
Jira ticket:
- SYS-4453
=> feat: add support for additional events

pallets/eth-bridge/src/lib.rs, pallets/eth-bridge/src/types.rs
Also deprecates older sudo extrinsics and consolidates under new one. Adds safeguards for additional events to ensure invariants are respected
Jira ticket:
- SYS-4453
=> feat: Adds sudo extrinsic to queue additional events

pallets/eth-bridge/src/lib.rs, pallets/eth-bridge/src/tests/tests.rs
Replicas of the old ones have been put under deprecated module
=> feat: Adds unit tests for new sudo extrinsic

node/avn-service/src/ethereum_events_handler.rs, pallets/eth-bridge/runtime-api/src/lib.rs, pallets/eth-bridge/src/benchmarking.rs, pallets/eth-bridge/src/lib.rs, pallets/eth-bridge/src/migration.rs, pallets/eth-bridge/src/tests/event_listener_tests.rs, pallets/eth-bridge/src/tests/incoming_events_tests.rs, pallets/eth-bridge/src/tests/tests.rs, pallets/eth-bridge/src/types.rs, primitives/avn-common/src/event_discovery.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
Extends the client implementation to support additional events during a range processing. Additional events must be from previous blocks of the range.
Extends the runtime API to provide these and the client implementation to consume it.
Adding new events is a sudo operation which is performed with a  new sudo extrinsic that consolidates previous entry points.
=> feat: Adds support for additional events

pallets/eth-bridge/src/tests/incoming_events_tests.rs, pallets/eth-bridge/src/tests/mock.rs, pallets/eth-bridge/src/tests/tests.rs
- Split the Context struct into multiple structs based on use case.
- Reorganize helper functions for better clarity and reuse.
- Add a test for events added from a future block rather than the one in the given range.
=> chore: refactor and extend tests

pallets/authors-manager/src/mock.rs, pallets/validators-manager/src/tests/mock.rs
Updates validators and authors manager mock setup to compile and pass.
=> fix: Update mocks for validators/authors manager

pallets/eth-bridge/src/tests/mock.rs, pallets/nft-manager/src/tests/mock.rs, pallets/token-manager/src/mock.rs
Fixes tests compilation errors on nft-manager and token manager.
Not all tests pass.
=> Update nft and token manager tests setup

pallets/avn-proxy/src/tests/mock.rs, pallets/parachain-staking/src/tests/mock.rs
Updates the mock setup in parachain staking and avn-proxy pallets.
=> fix: Fixes parachain testing and avn-proxy mocks 

pallets/avn-anchor/src/mock.rs
=> Make avn_anchor mock file to use default configs

.github/workflows/cargo-build.yml, .github/workflows/cargo-check.yml, .github/workflows/cargo-test.yml, .github/workflows/ci-cron.yml, .github/workflows/ci-main.yml, .github/workflows/ci-pr.yml, .github/workflows/docker-build.yml, .github/workflows/gh-release.yml, .github/workflows/manual-build.yaml, .github/workflows/s3-upload.yml, Dockerfile
Porting #498 into stable branch
=> chore: Add build step for AvN node on ubuntu 2404

.github/workflows/manual-build.yaml
Ports manual CI fix
https://github.com/AventusProtocolFoundation/avn-parachain/pull/511
=> fix: manual build step workflow 

.github/workflows/cargo-build.yml
=> DEVOPS-1110: Update Retention Days

.github/workflows/manual-build.yaml
=> fix: manual workflow fix port

.github/workflows/cargo-build.yml, .github/workflows/cargo-check.yml, .github/workflows/cargo-test.yml
fixes an issue where target is not automatically installed by the toolchain file
=> fixup: install target manually

Cargo.lock, Cargo.toml, runtime/avn/src/lib.rs
This PR consumes the latest commit from Substrate
=> Apply latest commit from substrate

Cargo.lock
This PR consumes the latest from Polkadot
=> Apply latest release from Polkadot

pallets/eth-bridge/src/benchmarking.rs, pallets/eth-bridge/src/call.rs, pallets/eth-bridge/src/eth.rs, pallets/eth-bridge/src/lib.rs, pallets/eth-bridge/src/migration.rs, pallets/eth-bridge/src/offence.rs, pallets/eth-bridge/src/request.rs, pallets/eth-bridge/src/tests/lower_proof_tests.rs, pallets/eth-bridge/src/tests/mock.rs, pallets/eth-bridge/src/tests/tests.rs, pallets/eth-bridge/src/tx.rs, pallets/eth-bridge/src/types.rs, pallets/eth-bridge/src/util.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
Refactors the eth-bridge pallet to enable multiple instances within a runtime. Includes interface changes and provides a default implementation for backward compatibility.
Updates runtime integration, tests, and benchmarks to align with the new structure. This commit focuses solely on refactoring the code to support multiple instances; any required changes to the pallet's logic will be introduced in subsequent commits.
Jira ticket:
- SYS-4558
=> feat: support multiple eth-bridge instances

pallets/parachain-staking/README.md, pallets/parachain-staking/src/lib.rs
- Improved documentation for reward distribution with clearer formulas.
- Simplified and structured the growth mechanism section for better readability.
- Added conditions and example flow for the growth mechanism.
Related Jira ticket:
- SYS-4519
=> docs(parachain-staking): clarify reward formulas and growth mechanism

pallets/avn/src/lib.rs, pallets/eth-bridge/src/call.rs, pallets/eth-bridge/src/eth.rs, pallets/eth-bridge/src/lib.rs, pallets/eth-bridge/src/request.rs, pallets/eth-bridge/src/tests/lower_proof_tests.rs, pallets/eth-bridge/src/tests/mock.rs, pallets/eth-bridge/src/tests/tests.rs, pallets/eth-bridge/src/tx.rs, pallets/eth-bridge/src/types.rs, pallets/parachain-staking/src/lib.rs, pallets/summary/src/lib.rs, pallets/summary/src/tests/mock.rs, pallets/validators-manager/src/lib.rs, primitives/avn-common/src/eth/mod.rs, primitives/avn-common/src/lib.rs
Moving signing operations into eth-bridge and primitive modules
Jira ticket:
- SYS-4560
=> feat: Refactor data structs and functions

Cargo.lock, node/avn-service/Cargo.toml, node/avn-service/src/lib.rs, pallets/avn/src/lib.rs, pallets/eth-bridge/src/eth.rs, pallets/eth-bridge/src/tests/lower_proof_tests.rs, pallets/eth-bridge/src/tests/mock.rs, pallets/eth-bridge/src/tests/tests.rs, pallets/validators-manager/src/tests/mock.rs, primitives/avn-common/src/eth/mod.rs, primitives/avn-common/src/lib.rs, runtime/avn/src/lib.rs
Updates data structs to match exactly the contract names and types as it causes the hash to be invalid.
=> fix: Alligns bridge data structs

pallets/avn-transaction-payment/src/lib.rs, pallets/avn-transaction-payment/src/tests/adjustment_fee_tests.rs, pallets/avn-transaction-payment/src/tests/mock.rs
This PR fixes a bug where gas fee refunds are not issued properly
=> Fix refund bug on LTS branch

node/avn-service/src/ethereum_events_handler.rs, pallets/eth-bridge/src/tests/event_listener_tests.rs, primitives/avn-common/src/event_discovery.rs, runtime/avn/src/lib.rs
Integrates version 3 of the eth-bridge runtime API Extends the client handler to iterate through all instances. Jira ticket:
- SYS-4561
=> feat!: updates the client integration of runtime API

node/avn-service/src/ethereum_events_handler.rs, node/avn-service/src/web3_utils.rs
Consolidates different functions for retrieving the chain_id and update the send function to include it in the transaction data.
References:
- M-07
- SYS-4665
=> fix: Adds chain-id when signing and sending a raw transaction.

pallets/authors-manager/src/mock.rs, pallets/avn-anchor/src/mock.rs, pallets/avn-proxy/src/tests/mock.rs, pallets/avn/src/lib.rs, pallets/eth-bridge/src/benchmarking.rs, pallets/eth-bridge/src/lib.rs, pallets/eth-bridge/src/tests/event_listener_tests.rs, pallets/eth-bridge/src/tests/lower_proof_tests.rs, pallets/eth-bridge/src/tests/mock.rs, pallets/eth-bridge/src/util.rs, pallets/parachain-staking/src/tests/mock.rs, pallets/summary/src/tests/mock.rs, pallets/token-manager/src/mock.rs, pallets/validators-manager/src/tests/mock.rs, primitives/avn-common/src/lib.rs, runtime/avn/src/lib.rs, runtime/test/src/lib.rs
Makes the quorum implementation a modular componenent that can be set via a interface in the EthBridge pallet.
Default implementation is added for the AvN pallet which is set as the default handler.
=> feat: make quorum configurable

Cargo.lock, pallets/summary/src/lib.rs, pallets/summary/src/tests/tests.rs, pallets/summary/src/tests/tests_challenge.rs, pallets/summary/src/tests/tests_vote.rs, primitives/avn-common/Cargo.toml, primitives/avn-common/src/lib.rs, primitives/avn-common/src/watchtower.rs
This PR adds watchtower basic types and infrastructure.
=> Adds watchower basic types and infrastructure - LTS branch

Cargo.lock, pallets/summary/src/lib.rs, primitives/avn-common/Cargo.toml, primitives/avn-common/src/lib.rs, primitives/avn-common/src/watchtower.rs, primitives/watchtower/Cargo.toml, primitives/watchtower/src/lib.rs
This PR adds watchtower basic types and infrastructure.
=> Adds watchower basic types and infrastructure
